---
title: "An examples of the workflow in the sd package"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{workflow}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(sd)
library(raster)
library(dplyr)
library(sf)
# library(tmap)
```

# Data

<!-- data intro -->
<!-- describe the data -->

```{r}
perc_raster
plot(perc_raster)
# tm_shape(perc_raster) + 
#   tm_raster(palette = "viridis", title = "Share of population:") +
#   tm_facets(free.scales = FALSE) +
# 	tm_layout(panel.labels = names(perc_raster))
```

# Create realizations

```{r}
real_raster = create_realizations(perc_raster, n = 5)
plot(real_raster)
# tm_shape(real_raster) + 
#   tm_raster(style = "cat", palette = "Set2", title = "Category:", 
#             labels = names(perc_raster)) +
#   tm_facets(free.scales = FALSE)
```

# Create weights

```{r}
weig_raster = create_weights(real_raster, perc_raster, size = 100)
plot(weig_raster)
# tm_shape(weig_raster) + 
#   tm_raster(palette = "viridis", title = "Weights:") +
#   tm_facets(free.scales = FALSE)
```

# Calculate metrics

```{r}
metr_df = calculate_metrics(real_raster, weig_raster,
                        neighbourhood = 4, fun = "mean", size = 100)
head(metr_df)
```

# Connect metrics to a grid

```{r}
grid_sf = create_grid(real_raster, size = 100)
grid_sf = dplyr::left_join(grid_sf, metr_df, by = c("row", "col"))
plot(filter(grid_sf, realization == 1))
# tm_shape(grid_sf) +
#   tm_polygons("ent", style = "cont") +
#   tm_facets(by = "realization")
```

