# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_motifels <- function(x, size, shift) {
    .Call('_racialscape_create_motifels', PACKAGE = 'racialscape', x, size, shift)
}

create_motifels_ids <- function(x, size, shift) {
    .Call('_racialscape_create_motifels_ids', PACKAGE = 'racialscape', x, size, shift)
}

draw_values <- function(x, y) {
    .Call('_racialscape_draw_values', PACKAGE = 'racialscape', x, y)
}

get_metrics <- function(x, w, directions, fun = "mean", na_action = "replace", base = "log2", ordered = TRUE, size = 0L, shift = 0L) {
    .Call('_racialscape_get_metrics', PACKAGE = 'racialscape', x, w, directions, fun, na_action, base, ordered, size, shift)
}

rcpp_ent <- function(x, base = "log2") {
    .Call('_racialscape_rcpp_ent', PACKAGE = 'racialscape', x, base)
}

rcpp_joinent <- function(x, base = "log2", ordered = TRUE) {
    .Call('_racialscape_rcpp_joinent', PACKAGE = 'racialscape', x, base, ordered)
}

rcpp_condent <- function(x, base = "log2", ordered = TRUE) {
    .Call('_racialscape_rcpp_condent', PACKAGE = 'racialscape', x, base, ordered)
}

rcpp_mutinf <- function(x, base = "log2", ordered = TRUE) {
    .Call('_racialscape_rcpp_mutinf', PACKAGE = 'racialscape', x, base, ordered)
}

motifel_areas <- function(x, size, shift) {
    .Call('_racialscape_motifel_areas', PACKAGE = 'racialscape', x, size, shift)
}

motifel_sums <- function(x, size, shift) {
    .Call('_racialscape_motifel_sums', PACKAGE = 'racialscape', x, size, shift)
}

motifel_adjustment <- function(x, y) {
    .Call('_racialscape_motifel_adjustment', PACKAGE = 'racialscape', x, y)
}

motifel_to_grid <- function(x, y, size, shift) {
    .Call('_racialscape_motifel_to_grid', PACKAGE = 'racialscape', x, y, size, shift)
}

rcpp_get_unique_values <- function(x, na_omit = TRUE) {
    .Call('_racialscape_rcpp_get_unique_values', PACKAGE = 'racialscape', x, na_omit)
}

