# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_motifels <- function(x, size) {
    .Call(`_sd_create_motifels`, x, size)
}

create_motifels_ids <- function(x, size) {
    .Call(`_sd_create_motifels_ids`, x, size)
}

draw_values <- function(x, y) {
    .Call(`_sd_draw_values`, x, y)
}

get_metrics <- function(x, w, directions, fun = "mean", na_action = "replace", base = "log2", ordered = TRUE, size = 0L) {
    .Call(`_sd_get_metrics`, x, w, directions, fun, na_action, base, ordered, size)
}

rcpp_ent <- function(x, base = "log2") {
    .Call(`_sd_rcpp_ent`, x, base)
}

rcpp_joinent <- function(x, base = "log2", ordered = TRUE) {
    .Call(`_sd_rcpp_joinent`, x, base, ordered)
}

rcpp_condent <- function(x, base = "log2", ordered = TRUE) {
    .Call(`_sd_rcpp_condent`, x, base, ordered)
}

rcpp_mutinf <- function(x, base = "log2", ordered = TRUE) {
    .Call(`_sd_rcpp_mutinf`, x, base, ordered)
}

motifel_areas <- function(x, size) {
    .Call(`_sd_motifel_areas`, x, size)
}

motifel_sums <- function(x, size) {
    .Call(`_sd_motifel_sums`, x, size)
}

motifel_adjustment <- function(x, y) {
    .Call(`_sd_motifel_adjustment`, x, y)
}

motifel_to_grid <- function(x, y, size) {
    .Call(`_sd_motifel_to_grid`, x, y, size)
}

rcpp_get_unique_values <- function(x, na_omit = TRUE) {
    .Call(`_sd_rcpp_get_unique_values`, x, na_omit)
}

